[package]
name = "iced_winit"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"

[features]
debug = []

[dependencies]
iced_native = { version = "0.1.0-alpha", path = "../native" }
winit = "0.20"
window_clipboard = { git = "https://github.com/hecrj/window_clipboard", rev = "22c6dd6c04cd05d528029b50a30c56417cd4bebf" }
futures = { version = "0.3", features = ["thread-pool"] }
log = "0.4"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
